### ISSUE TITLE
Possible timing bug in speed.cpp.

### ISSUE THREAD

**Issue by bipinmathew** [WojciechMula/simd-sort#5]
From my possibly flawed reading of the code, there appears to be a bug in speed.cpp that may produce invalid timing results. Specifically, I think this change needs to be made to speed.cpp:
```
bmathew@bmathew-desktop /tmp/simd-sort $ git diff speed.cpp
diff --git a/speed.cpp b/speed.cpp
index de0cf40..7292595 100644
--- a/speed.cpp
+++ b/speed.cpp
@@ -63,7 +63,7 @@ public:
 #ifdef USE_RDTSC
             RDTSC_START(t2);
 #else
-            t1 = get_time();
+            t2 = get_time();
 #endif
 
             const uint64_t dt = t2 - t1;
```
As it stands, I think t2 is uninitialized there and so produces invalid results.

**Comment by WojciechMula** [comment]
You're right! Thanks for spotting this.
